package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/blazing-Gael/dcms/internal/schema"
)

// tsBackend renders the TypeScript client: per-collection interfaces plus a
// fetch-based runtime whose calls map onto the real gateway routes and response
// envelopes. It is the flagship SDK; other languages implement Backend the same
// way, differing only in the scalar map and the template.
type tsBackend struct{}

func (tsBackend) Filename() string { return "dcms-client.ts" }

// TypeScript renders the TypeScript client for a schema. Thin wrapper kept for
// direct callers/tests; the general entry point is codegen.Generate.
func TypeScript(def *schema.SchemaDefinition) (string, error) {
	return tsBackend{}.Generate(BuildModel(def))
}

// tsType renders a field's TypeScript type for a given context. Relations are
// context-sensitive: an input takes the target id(s), whereas a response holds
// the id(s) OR — when `?expand=` is used — the expanded target object(s). Stripe
// popularized this "id or object" union; it lets one field serve both shapes.
func tsType(f Field, record bool) string {
	if f.Relation {
		if f.Many {
			if record {
				// Present only when expanded; the array holds target objects.
				return f.Target + "[]"
			}
			if f.NoInlineCreate {
				return "string[]" // media: ids only (created via upload)
			}
			// input: a list of target ids and/or inline records to create.
			return "(string | Create" + f.Target + ")[]"
		}
		// belongs-to
		if record {
			return "string | " + f.Target // the id, or the expanded object
		}
		if f.NoInlineCreate {
			return "string" // media: id only (created via upload)
		}
		return "string | Create" + f.Target // input: the id, or an inline record
	}
	return tsScalar(f)
}

// tsScalar maps a neutral Kind to a TypeScript type expression.
func tsScalar(f Field) string {
	switch f.Kind {
	case KindString, KindText, KindDate, KindDateTime:
		return "string"
	case KindNumber, KindInteger:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindEnum:
		if len(f.Enum) == 0 {
			return "string"
		}
		parts := make([]string, len(f.Enum))
		for i, v := range f.Enum {
			parts[i] = "'" + v + "'"
		}
		return strings.Join(parts, " | ")
	case KindRichText:
		return "RichText"
	case KindJSON:
		return "unknown"
	default:
		return "unknown"
	}
}

// tsField/tsColl/tsData are the template's view: the neutral model with each
// field's type pre-rendered into TypeScript.
type tsField struct {
	Name     string
	Type     string
	Optional bool
	ReadOnly bool
}

type tsColl struct {
	Collection string
	Type       string
	Record     []tsField
	Create     []tsField
	Update     []tsField
	Reserved   bool
	Publishing bool
	SoftDelete bool
}

type tsData struct {
	ContractVersion string
	BasePath        string
	Collections     []tsColl
}

// toTSFields renders fields for either the response record (record=true) or an
// input body (record=false); the flag drives how relation fields are typed.
func toTSFields(fields []Field, record bool) []tsField {
	out := make([]tsField, len(fields))
	for i, f := range fields {
		out[i] = tsField{Name: f.Name, Type: tsType(f, record), Optional: f.Optional, ReadOnly: f.ReadOnly}
	}
	return out
}

func (tsBackend) Generate(m Model) (string, error) {
	data := tsData{ContractVersion: m.ContractVersion, BasePath: m.BasePath}
	for _, c := range m.Collections {
		data.Collections = append(data.Collections, tsColl{
			Collection: c.Name,
			Type:       c.Type,
			Record:     toTSFields(c.Record, true),
			Create:     toTSFields(c.Create, false),
			Update:     toTSFields(c.Update, false),
			Reserved:   c.Reserved,
			Publishing: c.Publishing,
			SoftDelete: c.SoftDelete,
		})
	}

	tmpl, err := template.New("ts").Funcs(template.FuncMap{
		"bt": func() string { return "`" }, // a lone backtick, for TS template-literal types
	}).Parse(tsTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render template: %w", err)
	}
	return buf.String(), nil
}

// tsTemplate is the TypeScript module. The static runtime uses string
// concatenation (not template literals) so the whole file can live in a Go raw
// string; the one place TS needs backticks — the Sort<T> type — uses {{bt}}.
const tsTemplate = `// Code generated by ` + "`dcms codegen --lang ts`" + `. DO NOT EDIT.
//
// Contract version: {{.ContractVersion}}
// A fully-typed client for this DCMS instance. Regenerate after any schema
// change; if CONTRACT_VERSION no longer matches the server's, the types are stale.

export class DcmsError extends Error {
  constructor(
    message: string,
    readonly code: string,
    readonly status: number,
    readonly fields?: Record<string, string>,
  ) {
    super(message);
    this.name = "DcmsError";
  }
}

export interface ListMeta {
  total: number;
  limit: number;
  next_cursor: string | null;
}

export interface ListResult<T> {
  data: T[];
  meta: ListMeta;
  /** Reference manifest, present when ?expand= resolved richtext references (ADR-0015). */
  included?: Included;
}

// Structured rich content (ADR-0014): a portable-text-style document. A richtext
// field's value is an array of these nodes — text blocks with formatted spans,
// plus custom blocks (images, references, code, embeds) that may point at media
// or other records.
export interface RichTextSpan {
  _type: "span";
  text: string;
  marks?: string[]; // decorators (strong/em/…) or markDef _keys
}
export interface RichTextMarkDef {
  _key: string;
  _type: string; // "link" | "reference" | …
  [k: string]: unknown; // link: { href }, reference: { collection, ref }
}
export interface RichTextBlock {
  _type: "block";
  style?: string; // e.g. "normal", "h2", "blockquote"
  listItem?: "bullet" | "number";
  level?: number;
  children?: RichTextSpan[];
  markDefs?: RichTextMarkDef[];
}
// A custom (non-text) block: image/reference/code/embed. _type discriminates.
export interface RichTextObject {
  _type: string;
  [k: string]: unknown;
}
export type RichTextNode = RichTextBlock | RichTextObject;
export type RichText = RichTextNode[];

// The reference manifest returned at the response root by ?expand= on a richtext
// field (ADR-0015): resolved entities keyed "<collection>:<id>". The document AST
// stays id-only; resolve a node's ref against this map with resolveRef.
export type Included = Record<string, Record<string, unknown>>;

/**
 * resolveRef looks up the entity a richtext image/reference node (or reference
 * markDef) points at, from an included manifest. Returns undefined when the
 * target was hidden, missing, or the field was not expanded.
 */
export function resolveRef(
  included: Included | undefined,
  node: { _type?: string; ref?: string; collection?: string },
): Record<string, unknown> | undefined {
  if (!included || !node.ref) return undefined;
  const collection = node._type === "image" ? "_media" : node.collection;
  if (!collection) return undefined;
  return included[collection + ":" + node.ref];
}

export type FilterOps<V> = {
  eq?: V;
  ne?: V;
  gt?: V;
  gte?: V;
  lt?: V;
  lte?: V;
  contains?: string;
  starts_with?: string;
  in?: V[];
  nin?: V[];
};

export type Filter<T> = { [K in keyof T]?: T[K] | FilterOps<T[K]> };

export type Sort<T> = (keyof T & string) | {{bt}}-${keyof T & string}{{bt}};

export interface FindOptions<T> {
  filter?: Filter<T>;
  sort?: Sort<T>;
  limit?: number;
  cursor?: string;
  fields?: (keyof T & string)[];
  /** Comma-separated relation/richtext fields to inline (?expand=). */
  expand?: string[];
  /** Set false to skip the total row count for cheaper pages (meta.total omitted). */
  count?: boolean;
  /**
   * Lifecycle preview (ADR-0012). Only honored when the client sends a valid
   * preview token (set it via ClientOptions.headers as "X-DCMS-Preview");
   * otherwise these are ignored and only live, non-trashed records are returned.
   */
  status?: "draft" | "published" | "scheduled" | "archived" | "any";
  includeDeleted?: "true" | "only";
}

export interface Resource<T, TCreate, TUpdate> {
  find(options?: FindOptions<T>): Promise<ListResult<T>>;
  findOne(id: string): Promise<T>;
  create(input: TCreate): Promise<T>;
  update(id: string, input: TUpdate): Promise<T>;
  delete(id: string): Promise<void>;
}

/** Transition methods for a collection with publishing enabled (ADR-0012). */
export interface Publishable<T> {
  /** Publish now, or schedule by passing a future RFC3339 timestamp as at. */
  publish(id: string, at?: string): Promise<T>;
  unpublish(id: string): Promise<T>;
  archive(id: string): Promise<T>;
}

/** Transition methods for a collection with soft-delete enabled (ADR-0012). */
export interface SoftDeletable<T> {
  /** Undelete a soft-deleted (trashed) record. */
  restore(id: string): Promise<T>;
  /** Permanently delete, bypassing the trash. */
  purge(id: string): Promise<void>;
}

export type HeaderSource =
  | Record<string, string>
  | (() => Record<string, string> | Promise<Record<string, string>>);

export interface ClientOptions {
  /** Server origin, e.g. "https://cms.example.com". */
  url: string;
  /** Custom fetch (Node < 18, tests). Defaults to the global fetch. */
  fetch?: typeof fetch;
  /** Static headers or a function returning them (e.g. auth tokens). */
  headers?: HeaderSource;
}

const BASE_PATH = "{{.BasePath}}";
export const CONTRACT_VERSION = "{{.ContractVersion}}";

interface Config {
  origin: string;
  fetch: typeof fetch;
  headers?: HeaderSource;
}

function encodeQuery(opts: FindOptions<any>): string {
  const p = new URLSearchParams();
  if (opts.limit != null) p.set("limit", String(opts.limit));
  if (opts.cursor) p.set("cursor", opts.cursor);
  if (opts.sort) p.set("sort", opts.sort);
  if (opts.fields && opts.fields.length) p.set("fields", opts.fields.join(","));
  if (opts.expand && opts.expand.length) p.set("expand", opts.expand.join(","));
  if (opts.count === false) p.set("count", "false");
  if (opts.status) p.set("status", opts.status);
  if (opts.includeDeleted) p.set("include_deleted", opts.includeDeleted);
  if (opts.filter) {
    for (const field of Object.keys(opts.filter)) {
      const cond = (opts.filter as any)[field];
      if (cond == null) continue;
      if (typeof cond === "object" && !Array.isArray(cond)) {
        for (const op of Object.keys(cond)) {
          const val = cond[op];
          if (val === undefined) continue;
          const v = Array.isArray(val) ? val.join(",") : String(val);
          p.set("filter[" + field + "][" + op + "]", v);
        }
      } else {
        p.set("filter[" + field + "]", String(cond));
      }
    }
  }
  const s = p.toString();
  return s ? "?" + s : "";
}

async function resolveHeaders(h?: HeaderSource): Promise<Record<string, string>> {
  if (!h) return {};
  return typeof h === "function" ? await h() : h;
}

async function req(cfg: Config, method: string, path: string, body?: unknown): Promise<any> {
  const headers: Record<string, string> = { ...(await resolveHeaders(cfg.headers)) };
  const init: RequestInit = { method, headers };
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
    init.body = JSON.stringify(body);
  }
  const res = await cfg.fetch(cfg.origin + BASE_PATH + path, init);
  if (res.status === 204) return undefined;
  let parsed: any = undefined;
  try {
    parsed = await res.json();
  } catch {
    /* empty or non-JSON body */
  }
  if (!res.ok) {
    const e = (parsed && parsed.error) || {};
    throw new DcmsError(e.message || res.statusText, e.code || "ERROR", res.status, e.fields);
  }
  return parsed;
}

function resource<T, TCreate, TUpdate>(cfg: Config, collection: string): Resource<T, TCreate, TUpdate> {
  return {
    async find(options: FindOptions<T> = {}): Promise<ListResult<T>> {
      return (await req(cfg, "GET", "/" + collection + encodeQuery(options))) as ListResult<T>;
    },
    async findOne(id: string): Promise<T> {
      return (await req(cfg, "GET", "/" + collection + "/" + encodeURIComponent(id))).data as T;
    },
    async create(input: TCreate): Promise<T> {
      return (await req(cfg, "POST", "/" + collection, input)).data as T;
    },
    async update(id: string, input: TUpdate): Promise<T> {
      return (await req(cfg, "PATCH", "/" + collection + "/" + encodeURIComponent(id), input)).data as T;
    },
    async delete(id: string): Promise<void> {
      await req(cfg, "DELETE", "/" + collection + "/" + encodeURIComponent(id));
    },
  };
}

function publishable<T>(cfg: Config, collection: string): Publishable<T> {
  const at = (id: string) => "/" + collection + "/" + encodeURIComponent(id);
  return {
    async publish(id: string, when?: string): Promise<T> {
      return (await req(cfg, "POST", at(id) + "/publish", when ? { at: when } : undefined)).data as T;
    },
    async unpublish(id: string): Promise<T> {
      return (await req(cfg, "POST", at(id) + "/unpublish")).data as T;
    },
    async archive(id: string): Promise<T> {
      return (await req(cfg, "POST", at(id) + "/archive")).data as T;
    },
  };
}

function softDeletable<T>(cfg: Config, collection: string): SoftDeletable<T> {
  const at = (id: string) => "/" + collection + "/" + encodeURIComponent(id);
  return {
    async restore(id: string): Promise<T> {
      return (await req(cfg, "POST", at(id) + "/restore")).data as T;
    },
    async purge(id: string): Promise<void> {
      await req(cfg, "DELETE", at(id) + "?purge=true");
    },
  };
}

// ─── Generated types ────────────────────────────────────────────────────────
{{range .Collections}}
export interface {{.Type}} {
{{- range .Record}}
  {{if .ReadOnly}}readonly {{end}}{{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}
{{if not .Reserved}}
export interface Create{{.Type}} {
{{- range .Create}}
  {{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}

export interface Update{{.Type}} {
{{- range .Update}}
  {{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}
{{end}}{{end}}
// ─── Media library ──────────────────────────────────────────────────────────
const MEDIA_PATH = "/__media";

export interface MediaUploadInput {
  file: Blob | File;
  filename?: string;
  alt?: string;
  title?: string;
  caption?: string;
}

export interface MediaResource {
  list(options?: FindOptions<Media>): Promise<ListResult<Media>>;
  get(id: string): Promise<Media>;
  upload(input: MediaUploadInput): Promise<Media>;
  /** Replace the bytes of an existing asset, keeping its id and all references. */
  replace(id: string, file: Blob | File, filename?: string): Promise<Media>;
  /** Edit metadata only (alt/title/caption/filename). */
  update(id: string, meta: Partial<Pick<Media, "alt" | "title" | "caption" | "filename">>): Promise<Media>;
  delete(id: string): Promise<void>;
  /** The direct URL to an asset's bytes (for <img src>, downloads, etc.). */
  rawUrl(id: string): string;
}

function mediaClient(cfg: Config): MediaResource {
  const abs = (p: string) => cfg.origin + MEDIA_PATH + p;
  const parse = async (res: Response): Promise<any> => {
    if (res.status === 204) return undefined;
    let body: any = undefined;
    try { body = await res.json(); } catch { /* empty */ }
    if (!res.ok) {
      const e = (body && body.error) || {};
      throw new DcmsError(e.message || res.statusText, e.code || "ERROR", res.status, e.fields);
    }
    return body;
  };
  const send = async (path: string, file: Blob | File, meta: Record<string, string | undefined>): Promise<Media> => {
    const fd = new FormData();
    fd.append("file", file, meta.filename || undefined);
    for (const k of ["alt", "title", "caption"]) {
      const v = meta[k];
      if (v != null) fd.append(k, v);
    }
    const res = await cfg.fetch(abs(path), { method: "POST", headers: await resolveHeaders(cfg.headers), body: fd });
    return (await parse(res)).data as Media;
  };
  return {
    async list(options: FindOptions<Media> = {}): Promise<ListResult<Media>> {
      const res = await cfg.fetch(abs("/" + encodeQuery(options)), { method: "GET", headers: await resolveHeaders(cfg.headers) });
      return (await parse(res)) as ListResult<Media>;
    },
    async get(id: string): Promise<Media> {
      const res = await cfg.fetch(abs("/" + encodeURIComponent(id)), { method: "GET", headers: await resolveHeaders(cfg.headers) });
      return (await parse(res)).data as Media;
    },
    async upload(input: MediaUploadInput): Promise<Media> {
      return send("/", input.file, { filename: input.filename, alt: input.alt, title: input.title, caption: input.caption });
    },
    async replace(id: string, file: Blob | File, filename?: string): Promise<Media> {
      return send("/" + encodeURIComponent(id), file, { filename });
    },
    async update(id: string, meta: Partial<Pick<Media, "alt" | "title" | "caption" | "filename">>): Promise<Media> {
      const headers = { ...(await resolveHeaders(cfg.headers)), "Content-Type": "application/json" };
      const res = await cfg.fetch(abs("/" + encodeURIComponent(id)), { method: "PATCH", headers, body: JSON.stringify(meta) });
      return (await parse(res)).data as Media;
    },
    async delete(id: string): Promise<void> {
      await parse(await cfg.fetch(abs("/" + encodeURIComponent(id)), { method: "DELETE", headers: await resolveHeaders(cfg.headers) }));
    },
    rawUrl(id: string): string {
      return cfg.origin + MEDIA_PATH + "/" + encodeURIComponent(id) + "/raw";
    },
  };
}

// ─── Auth ───────────────────────────────────────────────────────────────────
const AUTH_PATH = "/auth";

export interface Principal {
  id: string;
  roles: string[];
  email?: string;
  name?: string;
}

export interface LoginResult {
  token: string;
  expires_at: string;
  user: Principal;
}

export interface AuthResource {
  /** Exchange email + password for an opaque session token (also set as a cookie). */
  login(email: string, password: string): Promise<LoginResult>;
  /** Revoke the current session (idempotent). */
  logout(): Promise<void>;
  /** The current principal; throws DcmsError with status 401 when unauthenticated. */
  me(): Promise<Principal>;
}

function authClient(cfg: Config): AuthResource {
  const abs = (p: string) => cfg.origin + AUTH_PATH + p;
  const parse = async (res: Response): Promise<any> => {
    if (res.status === 204) return undefined;
    let body: any = undefined;
    try { body = await res.json(); } catch { /* empty */ }
    if (!res.ok) {
      const e = (body && body.error) || {};
      throw new DcmsError(e.message || res.statusText, e.code || "ERROR", res.status, e.fields);
    }
    return body;
  };
  return {
    async login(email: string, password: string): Promise<LoginResult> {
      const headers = { ...(await resolveHeaders(cfg.headers)), "Content-Type": "application/json" };
      const res = await cfg.fetch(abs("/login"), { method: "POST", headers, body: JSON.stringify({ email, password }) });
      return (await parse(res)) as LoginResult;
    },
    async logout(): Promise<void> {
      await parse(await cfg.fetch(abs("/logout"), { method: "POST", headers: await resolveHeaders(cfg.headers) }));
    },
    async me(): Promise<Principal> {
      const res = await cfg.fetch(abs("/me"), { method: "GET", headers: await resolveHeaders(cfg.headers) });
      return (await parse(res)).data as Principal;
    },
  };
}

// ─── Client ─────────────────────────────────────────────────────────────────
export interface DcmsClient {
  readonly contractVersion: string;
  auth: AuthResource;
  media: MediaResource;
{{- range .Collections}}{{if not .Reserved}}
  {{.Collection}}: Resource<{{.Type}}, Create{{.Type}}, Update{{.Type}}>{{if .Publishing}} & Publishable<{{.Type}}>{{end}}{{if .SoftDelete}} & SoftDeletable<{{.Type}}>{{end}};
{{- end}}{{- end}}
}

export function createClient(options: ClientOptions): DcmsClient {
  const cfg: Config = {
    origin: options.url.replace(/\/+$/, ""),
    fetch: options.fetch ?? globalThis.fetch,
    headers: options.headers,
  };
  return {
    contractVersion: CONTRACT_VERSION,
    auth: authClient(cfg),
    media: mediaClient(cfg),
{{- range .Collections}}{{if not .Reserved}}
    {{.Collection}}: Object.assign(resource<{{.Type}}, Create{{.Type}}, Update{{.Type}}>(cfg, "{{.Collection}}"){{if .Publishing}}, publishable<{{.Type}}>(cfg, "{{.Collection}}"){{end}}{{if .SoftDelete}}, softDeletable<{{.Type}}>(cfg, "{{.Collection}}"){{end}}),
{{- end}}{{- end}}
  };
}
`
