package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/blazing-Gael/dcms/internal/schema"
)

// tsBackend renders the TypeScript client: per-collection interfaces plus a
// fetch-based runtime whose calls map onto the real gateway routes and response
// envelopes. It is the flagship SDK; other languages implement Backend the same
// way, differing only in the scalar map and the template.
type tsBackend struct{}

func (tsBackend) Filename() string { return "dcms-client.ts" }

// TypeScript renders the TypeScript client for a schema. Thin wrapper kept for
// direct callers/tests; the general entry point is codegen.Generate.
func TypeScript(def *schema.SchemaDefinition) (string, error) {
	return tsBackend{}.Generate(BuildModel(def))
}

// tsType renders a field's TypeScript type for a given context. Relations are
// context-sensitive: an input takes the target id(s), whereas a response holds
// the id(s) OR — when `?expand=` is used — the expanded target object(s). Stripe
// popularized this "id or object" union; it lets one field serve both shapes.
func tsType(f Field, record bool) string {
	if f.Relation {
		if f.Many {
			if record {
				// Present only when expanded; the array holds target objects.
				return f.Target + "[]"
			}
			// input: a list of target ids and/or inline records to create.
			return "(string | Create" + f.Target + ")[]"
		}
		// belongs-to
		if record {
			return "string | " + f.Target // the id, or the expanded object
		}
		return "string | Create" + f.Target // input: the id, or an inline record
	}
	return tsScalar(f)
}

// tsScalar maps a neutral Kind to a TypeScript type expression.
func tsScalar(f Field) string {
	switch f.Kind {
	case KindString, KindText, KindDate, KindDateTime:
		return "string"
	case KindNumber, KindInteger:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindEnum:
		if len(f.Enum) == 0 {
			return "string"
		}
		parts := make([]string, len(f.Enum))
		for i, v := range f.Enum {
			parts[i] = "'" + v + "'"
		}
		return strings.Join(parts, " | ")
	case KindJSON:
		return "unknown"
	default:
		return "unknown"
	}
}

// tsField/tsColl/tsData are the template's view: the neutral model with each
// field's type pre-rendered into TypeScript.
type tsField struct {
	Name     string
	Type     string
	Optional bool
	ReadOnly bool
}

type tsColl struct {
	Collection string
	Type       string
	Record     []tsField
	Create     []tsField
	Update     []tsField
}

type tsData struct {
	ContractVersion string
	BasePath        string
	Collections     []tsColl
}

// toTSFields renders fields for either the response record (record=true) or an
// input body (record=false); the flag drives how relation fields are typed.
func toTSFields(fields []Field, record bool) []tsField {
	out := make([]tsField, len(fields))
	for i, f := range fields {
		out[i] = tsField{Name: f.Name, Type: tsType(f, record), Optional: f.Optional, ReadOnly: f.ReadOnly}
	}
	return out
}

func (tsBackend) Generate(m Model) (string, error) {
	data := tsData{ContractVersion: m.ContractVersion, BasePath: m.BasePath}
	for _, c := range m.Collections {
		data.Collections = append(data.Collections, tsColl{
			Collection: c.Name,
			Type:       c.Type,
			Record:     toTSFields(c.Record, true),
			Create:     toTSFields(c.Create, false),
			Update:     toTSFields(c.Update, false),
		})
	}

	tmpl, err := template.New("ts").Funcs(template.FuncMap{
		"bt": func() string { return "`" }, // a lone backtick, for TS template-literal types
	}).Parse(tsTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render template: %w", err)
	}
	return buf.String(), nil
}

// tsTemplate is the TypeScript module. The static runtime uses string
// concatenation (not template literals) so the whole file can live in a Go raw
// string; the one place TS needs backticks — the Sort<T> type — uses {{bt}}.
const tsTemplate = `// Code generated by ` + "`dcms codegen --lang ts`" + `. DO NOT EDIT.
//
// Contract version: {{.ContractVersion}}
// A fully-typed client for this DCMS instance. Regenerate after any schema
// change; if CONTRACT_VERSION no longer matches the server's, the types are stale.

export class DcmsError extends Error {
  constructor(
    message: string,
    readonly code: string,
    readonly status: number,
    readonly fields?: Record<string, string>,
  ) {
    super(message);
    this.name = "DcmsError";
  }
}

export interface ListMeta {
  total: number;
  limit: number;
  next_cursor: string | null;
}

export interface ListResult<T> {
  data: T[];
  meta: ListMeta;
}

export type FilterOps<V> = {
  eq?: V;
  ne?: V;
  gt?: V;
  gte?: V;
  lt?: V;
  lte?: V;
  contains?: string;
  starts_with?: string;
  in?: V[];
  nin?: V[];
};

export type Filter<T> = { [K in keyof T]?: T[K] | FilterOps<T[K]> };

export type Sort<T> = (keyof T & string) | {{bt}}-${keyof T & string}{{bt}};

export interface FindOptions<T> {
  filter?: Filter<T>;
  sort?: Sort<T>;
  limit?: number;
  cursor?: string;
  fields?: (keyof T & string)[];
}

export interface Resource<T, TCreate, TUpdate> {
  find(options?: FindOptions<T>): Promise<ListResult<T>>;
  findOne(id: string): Promise<T>;
  create(input: TCreate): Promise<T>;
  update(id: string, input: TUpdate): Promise<T>;
  delete(id: string): Promise<void>;
}

export type HeaderSource =
  | Record<string, string>
  | (() => Record<string, string> | Promise<Record<string, string>>);

export interface ClientOptions {
  /** Server origin, e.g. "https://cms.example.com". */
  url: string;
  /** Custom fetch (Node < 18, tests). Defaults to the global fetch. */
  fetch?: typeof fetch;
  /** Static headers or a function returning them (e.g. auth tokens). */
  headers?: HeaderSource;
}

const BASE_PATH = "{{.BasePath}}";
export const CONTRACT_VERSION = "{{.ContractVersion}}";

interface Config {
  origin: string;
  fetch: typeof fetch;
  headers?: HeaderSource;
}

function encodeQuery(opts: FindOptions<any>): string {
  const p = new URLSearchParams();
  if (opts.limit != null) p.set("limit", String(opts.limit));
  if (opts.cursor) p.set("cursor", opts.cursor);
  if (opts.sort) p.set("sort", opts.sort);
  if (opts.fields && opts.fields.length) p.set("fields", opts.fields.join(","));
  if (opts.filter) {
    for (const field of Object.keys(opts.filter)) {
      const cond = (opts.filter as any)[field];
      if (cond == null) continue;
      if (typeof cond === "object" && !Array.isArray(cond)) {
        for (const op of Object.keys(cond)) {
          const val = cond[op];
          if (val === undefined) continue;
          const v = Array.isArray(val) ? val.join(",") : String(val);
          p.set("filter[" + field + "][" + op + "]", v);
        }
      } else {
        p.set("filter[" + field + "]", String(cond));
      }
    }
  }
  const s = p.toString();
  return s ? "?" + s : "";
}

async function resolveHeaders(h?: HeaderSource): Promise<Record<string, string>> {
  if (!h) return {};
  return typeof h === "function" ? await h() : h;
}

async function req(cfg: Config, method: string, path: string, body?: unknown): Promise<any> {
  const headers: Record<string, string> = { ...(await resolveHeaders(cfg.headers)) };
  const init: RequestInit = { method, headers };
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
    init.body = JSON.stringify(body);
  }
  const res = await cfg.fetch(cfg.origin + BASE_PATH + path, init);
  if (res.status === 204) return undefined;
  let parsed: any = undefined;
  try {
    parsed = await res.json();
  } catch {
    /* empty or non-JSON body */
  }
  if (!res.ok) {
    const e = (parsed && parsed.error) || {};
    throw new DcmsError(e.message || res.statusText, e.code || "ERROR", res.status, e.fields);
  }
  return parsed;
}

function resource<T, TCreate, TUpdate>(cfg: Config, collection: string): Resource<T, TCreate, TUpdate> {
  return {
    async find(options: FindOptions<T> = {}): Promise<ListResult<T>> {
      return (await req(cfg, "GET", "/" + collection + encodeQuery(options))) as ListResult<T>;
    },
    async findOne(id: string): Promise<T> {
      return (await req(cfg, "GET", "/" + collection + "/" + encodeURIComponent(id))).data as T;
    },
    async create(input: TCreate): Promise<T> {
      return (await req(cfg, "POST", "/" + collection, input)).data as T;
    },
    async update(id: string, input: TUpdate): Promise<T> {
      return (await req(cfg, "PATCH", "/" + collection + "/" + encodeURIComponent(id), input)).data as T;
    },
    async delete(id: string): Promise<void> {
      await req(cfg, "DELETE", "/" + collection + "/" + encodeURIComponent(id));
    },
  };
}

// ─── Generated types ────────────────────────────────────────────────────────
{{range .Collections}}
export interface {{.Type}} {
{{- range .Record}}
  {{if .ReadOnly}}readonly {{end}}{{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}

export interface Create{{.Type}} {
{{- range .Create}}
  {{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}

export interface Update{{.Type}} {
{{- range .Update}}
  {{.Name}}{{if .Optional}}?{{end}}: {{.Type}};
{{- end}}
}
{{end}}
// ─── Client ─────────────────────────────────────────────────────────────────
export interface DcmsClient {
  readonly contractVersion: string;
{{- range .Collections}}
  {{.Collection}}: Resource<{{.Type}}, Create{{.Type}}, Update{{.Type}}>;
{{- end}}
}

export function createClient(options: ClientOptions): DcmsClient {
  const cfg: Config = {
    origin: options.url.replace(/\/+$/, ""),
    fetch: options.fetch ?? globalThis.fetch,
    headers: options.headers,
  };
  return {
    contractVersion: CONTRACT_VERSION,
{{- range .Collections}}
    {{.Collection}}: resource<{{.Type}}, Create{{.Type}}, Update{{.Type}}>(cfg, "{{.Collection}}"),
{{- end}}
  };
}
`
